{% set name = "qcmanybody" %}
{% set version = "0.4.0" %}
{% set sha256 = "6a23883074bb0d328e8099f6f47d04c3b3e74ba2dde483a8b8c86c9211cc942d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
    - setuptools-scm >=8.0
  run:
    - qcelemental
    - numpy
    - pydantic >=1.8.2
    - python >=3.8.0

test:
  imports:
    - qcmanybody
  requires:
    - pytest >=7.0.0
    - zstandard
    - pip
  commands:
    - test -f $SP_DIR/qcmanybody/__init__.py
    - pip check
    - python -c "import qcmanybody as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
    - pytest --pyargs qcmanybody

about:
  home: https://github.com/MolSSI/QCManyBody
  dev_url: https://github.com/MolSSI/QCManyBody
  doc_url: https://molssi.github.io/QCManyBody/
  doc_source_url: https://github.com/MolSSI/QCManyBody/blob/main/docs/index.md
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: QCManyBody is an intermolecular many-body expansion module with QCArchive integration

extra:
  recipe-maintainers:
    - loriab
    - bennybp
