{% set name = "qcmanybody" %}
{% set version = "0.1.0" %}
{% set sha256 = "0c16f208f1482b2731a554ee704bbd8f66f82520c16ac551a1ee35e146933bc9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - qcelemental
    - qcengine
    - numpy
    - pydantic >=1.8.2
    - python >=3.8.0

test:
  imports:
    - qcmanybody
  requires:
    - pytest >=7.0.0
    - zstandard
    - pip
  commands:
    - pip check
    - pytest --pyargs qcmanybody

about:
  home: https://github.com/MolSSI/QCManyBody
  dev_url: https://github.com/MolSSI/QCManyBody
  doc_url: https://molssi.github.io/QCManyBody/
  doc_source_url: https://github.com/MolSSI/QCManyBody/blob/main/docs/index.md
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: QCManyBody is an intermolecular many-body expansion module with QCArchive integration

extra:
  recipe-maintainers:
    - loriab
    - bennybp
